package com.caiyu.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.caiyu.entity.ClassTableEntity;
import com.caiyu.entity.ClassTimeEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 *
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig classTableDaoConfig;
    private final DaoConfig classTimeDaoConfig;

    private final ClassTableDao classTableDao;
    private final ClassTimeDao classTimeDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        classTableDaoConfig = daoConfigMap.get(ClassTableDao.class).clone();
        classTimeDaoConfig = daoConfigMap.get(ClassTimeDao.class).clone();
        classTableDaoConfig.initIdentityScope(type);
        classTimeDaoConfig.initIdentityScope(type);

        classTableDao = new ClassTableDao(classTableDaoConfig, this);
        classTimeDao = new ClassTimeDao(classTimeDaoConfig, this);

        registerDao(ClassTableEntity.class, classTableDao);
        registerDao(ClassTimeEntity.class, classTimeDao);
    }

    public void clear() {
        classTableDaoConfig.getIdentityScope().clear();
        classTimeDaoConfig.getIdentityScope().clear();
    }

    public ClassTableDao getClassTableDao() {
        return classTableDao;
    }

    public ClassTimeDao getClassTimeDao() {
        return classTimeDao;
    }
}
