package com.caiyu.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table class_table.
 */
public class ClassTableEntity {

    private Long id;
    private Integer day_of_week;
    private Integer order_of_day;
    private String class_name;
    private String class_room;
    private String teacher;
    private Integer start_week;
    private Integer end_week;
    private Long subject_id;

    public ClassTableEntity() {
    }

    public ClassTableEntity(Long id) {
        this.id = id;
    }

    public ClassTableEntity(Long id, Integer day_of_week, Integer order_of_day, String class_name, String class_room, String teacher, Integer start_week, Integer end_week, Long subject_id) {
        this.id = id;
        this.day_of_week = day_of_week;
        this.order_of_day = order_of_day;
        this.class_name = class_name;
        this.class_room = class_room;
        this.teacher = teacher;
        this.start_week = start_week;
        this.end_week = end_week;
        this.subject_id = subject_id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getDayOfWeek() {
        return day_of_week;
    }

    public void setDayOfWeek(Integer day_of_week) {
        this.day_of_week = day_of_week;
    }

    public Integer getOrderOfDay() {
        return order_of_day;
    }

    public void setOrderOfDay(Integer order_of_day) {
        this.order_of_day = order_of_day;
    }

    public String getClassName() {
        return class_name;
    }

    public void setClassName(String class_name) {
        this.class_name = class_name;
    }

    public String getClassRoom() {
        return class_room;
    }

    public void setClassRoom(String class_room) {
        this.class_room = class_room;
    }

    public String getTeacher() {
        return teacher;
    }

    public void setTeacher(String teacher) {
        this.teacher = teacher;
    }

    public Integer getStartWeek() {
        return start_week;
    }

    public void setStartWeek(Integer start_week) {
        this.start_week = start_week;
    }

    public Integer getEndWeek() {
        return end_week;
    }

    public void setEndWeek(Integer end_week) {
        this.end_week = end_week;
    }

    public Long getSubjectId() {
        return subject_id;
    }

    public void setSubjectId(Long subject_id) {
        this.subject_id = subject_id;
    }
}
